# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: 'default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install Nuget tools'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Source file location
      $source = 'https://dist.nuget.org/win-x86-commandline/v6.0.0-preview3/nuget.exe'
      # Destination to save the file
      $destination = '$(Agent.TempDirectory)\nuget.exe'
      #Download the file
      Invoke-WebRequest -Uri $source -OutFile $destination

- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg' # Options: nugetOrg, customFeed, netShare
    versionSelector: 'latestPreRelease' 

- task: UseDotNet@2
  inputs:
    version: '5.0.x'
    includePreviewVersions: true # Required for preview versions

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 5.0.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions

- task: DotNetCoreCLI@2
  inputs:
    commands: 'build'
    publishTestResults: true
    verbosityPack: 'diagnostic'

- task: VSTest@2
  displayName: 'Run Unit Tests'
  inputs:
    vsTestVersion: 'toolsInstaller'
    testAssemblyVer2: '**/bin/$(buildConfiguration)/*.dll'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: true
    runTestsInIsolation: true
    resultsFolder: '$(System.DefaultWorkingDirectory)/TestResults'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TestResults/*.trx' 
