# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
- linux-container

pool:
  name: 'default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install Nuget tools'

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.0.x
    performMultiLevelLookup: true
    includePreviewVersions: true
    # dotnet tool install dotnet-vstest
- task: DotNetCoreCLI@2
  displayName: 'Building'
  inputs:
    commands: 'build'
    verbosityPack: 'diagnostic'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    arguments: --logger trx --results-directory "/azp/_work/_temp/TestResults/"
    publishTestResults: false
    verbosityPack: 'diagnostic'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '/azp/_work/_temp/TestResults/*.trx' 
