# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
- linux-container
- custom

pool:
  name: 'default'

variables:
  Major: '0'
  Minor: '0'
  Patch: '0'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install Nuget tools'

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.0.x
    performMultiLevelLookup: true
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Building'
  inputs:
    commands: 'build'
    verbosityPack: 'diagnostic'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    arguments: --logger trx --results-directory "$(Agent.TempDirectory)/TestResults/"
    publishTestResults: false
    verbosityPack: 'diagnostic'

- task: DotNetCoreCLI@2
  displayName: 'VSTest'
  inputs:
    command: 'custom'
    custom: 'vstest'
    arguments: $(Agent.BuildDirectory)/s/Spike/bin/Debug/net6.0/Spike.dll --logger:trx;logfilename=Test.xml

- task: NuGetCommand@2
  displayName: 'Pack'
  inputs:
    command: pack
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
    packagesToPack: '**/*.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    commands: 'publish'
    nobuild: true
    feedsToUse: config
    nugetConfigPath: $(Build.Repository.LocalPath)/Spike/
    verbosityPack: 'diagnostic'

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'CAM/TKONFeed'
    allowPackageConflicts: true

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '$(Agent.TempDirectory)/TestResults/*.trx' 
